usage = "Use this material when asked to create content for a 10Clouds SEO landing page"
content_type = "static_text"
content_static_text = """
# Generic guidelines

If you do not have specific and detailed information on a given service in your memory or materials ask for additionall information before you continue with generating content.
Before starting to work on specific content write down your understanding of the service and then confirm that it's correct.

# Title & Short Description

Create a title and description of previously described services that will attract CTOs, Engineering Managers, CEOs and Product Managers at technology companies. Use the following format:

Title, catchy and to the point, include 1 SEO keyword in it, max 60 characters. 

Description, specific, Include 1 SEO keyword and 1 variation of it, max 200 characters. 

# Services short

Propose 4 services that 10Clouds can offer to its customers based on the Service.
Each service proposal must be in a format:

Service Title ( 1 sentence )
Service description (1 sentence)

# Use cases

Create 6 examples of use cases that could benefit from using before mentioned service. In the use case description focus on benefits for the customer.
Each use case must be in format format:

Use case title ( up too 30 characters )
Use case description and benefits (up too 190 characters)

# Benefits

Propose only the requested content, avoid any intro text or summaries of 10Clouds.
Create 6 benefits of working with 10Clouds based of this specific service description. Include statistics and specific numbers if possible. Dont propose generic 10Clouds benefits.

Each benefit must be in following format:
Benefit title, up too 30 character
Benefit description up too 190 characters

# FAQ

Based on the specific service  create: 

6 questions and answers for most common question that could appear in relation to this service. Make it as a FAQ in a format:


Q:(uestion): 1 sentence, max 190 characters
A:(answear) 1 paragraph, max 400 characters
"""
