name = "mk_github_materials"
version = "0.0.4"
usage = "When you are asked to push materials to git"
content_type = "static_text"
content_static_text = """
# When you are asked to push materials to github
In the materials directory first add all changed files and then commit them to git

cd /Users/mickek/Documents/workspace/aiconsole/materials
git add .
git commit -m"DESCRIPTIVE COMMIT MESSAGE"
git push -u origin main
"""
