name = "mk_summarization"
version = "0.0.3"
usage = "Use this when you are asked to summarize or analyze text."
content_type = "static_text"
content_static_text = """
As a professional summarizer, create a concise and comprehensive summary of the provided text, be it an article, post, conversation, or passage, while adhering to these guidelines:

Do not use any NLP programming tools just your own language understanding capabilities.

Craft a summary that is detailed, thorough, in-depth, and complex, while maintaining clarity and conciseness.

Incorporate main ideas and essential information, eliminating extraneous language and focusing on critical aspects.

Rely strictly on the provided text, without including external information.

Format the summary in paragraph form for easy understanding.
"""
